In [79]:
# BHAVYA GUPTA
# 2021-07-25
#ASSIGNMENT 5 NUMPY

import numpy as np

In [80]:
#3.Reversing an array

arr1 = np.array([1, 2, 3, 4, 5])
reversed_arr = arr1[::-1]
print(reversed_arr)  

arr2 = np.array([[1, 2], [3, 4], [5, 6]])
reversed_rows = arr2[::-1, :]
print(reversed_rows)  


[5 4 3 2 1]
[[5 6]
 [3 4]
 [1 2]]


In [81]:
flipped_rows = np.flip(arr2, axis=0)
print(flipped_rows)  
print()
flipped_columns = np.flip(arr2, axis=1)
print(flipped_columns)  

[[5 6]
 [3 4]
 [1 2]]

[[2 1]
 [4 3]
 [6 5]]


In [82]:
#4. Checkinf the datatypes

arr = np.array([1, 2, 3])
print(arr.dtype) 

arr = np.empty((10,10,10)) 
print(arr.dtype)

int32
float64


In [83]:
#7. comparing vstack and hstack
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)),"\n")

print(np.hstack((a, b)))


[[1 2]
 [3 4]] 

[1 2 3 4]


In [84]:
#8. Differences between fliplr() and flipud()
arr = np.array([[1, 2], 
                [3, 4]])
np.fliplr(arr)  ,(), np.flipud(arr)  



(array([[2, 1],
        [4, 3]]),
 (),
 array([[3, 4],
        [1, 2]]))

In [85]:
#9. Array_split method

arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 3)  

[array([1, 2]), array([3, 4]), array([5])]

In [86]:
#10. Vectorization
arr = np.array([1, 2, 3])
arr = arr + 1  
arr

array([2, 3, 4])

In [87]:
#10. Broadcasting
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
arr + scalar 

array([[3, 4, 5],
       [6, 7, 8]])

PRACTICAL QUESTIONS 

In [88]:
import numpy as np


In [89]:
#1. Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print(arr,"\n")

transposed_arr = arr.T
print(transposed_arr)


[[99 93 86]
 [64 36 85]
 [62  6 61]] 

[[99 64 62]
 [93 36  6]
 [86 85 61]]


In [90]:
#2. Generate a 1D array with 10 elements
arr = np.arange(10)

reshaped_2x5 = arr.reshape(2, 5)
print(reshaped_2x5)
print()

reshaped_5x2 = arr.reshape(5, 2)
print(reshaped_5x2)

reshaped_7x = arr.reshape(10,-1)
print(reshaped_7x)


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [91]:
#3. Create a 4x4 array with random float values
arr = np.random.rand(4, 4)

padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_arr)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.74894955 0.03210986 0.77315852 0.67220188 0.        ]
 [0.         0.92748349 0.37086618 0.28828447 0.76693038 0.        ]
 [0.         0.30695306 0.53628249 0.69329662 0.32268613 0.        ]
 [0.         0.88958973 0.81652017 0.42821598 0.00577011 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [92]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [93]:
#5. Creating arraay of strings and applying different case transformers to them.
arr = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)

print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [94]:
#6. Generating np array of words
arr = np.array(['this', 'is','a', 'numpy','array'])

spaced_arr = np.char.join(' ', arr)
print(spaced_arr)


['t h i s' 'i s' 'a' 'n u m p y' 'a r r a y']


In [95]:
#7. Applying element-wise addition ,sub,mul,div
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [96]:
#8. Creating a 5x5 identity mat

arr = np.eye(5,5)
print(arr)

diagonal = np.diag(arr)
print("Diagonal Elements of Identity Matrix:")
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements of Identity Matrix:
[1. 1. 1. 1. 1.]


In [150]:
#9. Finding all prime no in 100 random ints arr 
arr = np.random.randint(0, 1000, 100)

def is_prime(n):
    if n < 2:
        return False
    for j in range(2, n):
        if n % j == 0:
            return False
    return True


prime_numbers = [num for num in arr if is_prime(num)]

print("Random array:", arr)
print("Prime numbers in the array:", set(prime_numbers))



Random array: [207 708 754  60 737  70 198 377 396 805 155 702 756 951 480 240 123 537
 532 583  65 989 582 418 496 827  71  84 760 163 821 212  59 384 371 771
 604 918 685 306 934 241 708  87 306 289 388 647 159 664 270  39 790 186
 411 663 471 755 388 660 867 555 682  78 607 220 872 131 107 617 407 627
 577 206 708 617 296 214 168 118 436  53 698 334 639 467 312 543 643 627
 698 270 424 777 600 541 987 400 277 564]
Prime numbers in the array: {827, 577, 163, 131, 643, 71, 647, 617, 107, 241, 467, 821, 53, 277, 59, 541, 607}


In [158]:
#10. display monthly and weekly avg of temps
temperatures = np.random.randint(20, 40, size=30)

temperatures_per_week = temperatures[:28].reshape(4, 7)

weekly_averages = np.mean(temperatures_per_week, axis=1)

print("Weekly Averages:")
print(weekly_averages)
print("temps = ",temperatures)
print("temps per week = ",temperatures_per_week)


Weekly Averages:
[25.71428571 30.         30.28571429 32.28571429]
temps =  [22 28 29 31 27 21 22 24 25 33 33 31 33 31 28 38 24 22 30 38 32 22 23 36
 39 39 30 37 35 21]
temps per week =  [[22 28 29 31 27 21 22]
 [24 25 33 33 31 33 31]
 [28 38 24 22 30 38 32]
 [22 23 36 39 39 30 37]]
